version: '3.8'

services:
  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-tracker-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 8000
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@resend.dev}
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - expense-tracker-network

  # Frontend React App  
  frontend:
    build: 
      context: ./frontend/expense-tracker
      dockerfile: Dockerfile
    container_name: expense-tracker-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    depends_on:
      - backend
    networks:
      - expense-tracker-network

# Networks
networks:
  expense-tracker-network:
    driver: bridge